/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate and obtain a JWT token
         * @description Validates username and password, returns a JWT token and user profile on success.
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out and invalidate the current session
         * @description Invalidates the current JWT token. Client should discard the token.
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh an expiring JWT token
         * @description Issues a new JWT token with an extended expiry. Requires a valid (non-expired) token.
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error object returned in the envelope when a request fails. */
        ErrorResponse: {
            /**
             * @description HTTP status code
             * @example 404
             */
            code: number;
            /**
             * @description Human-readable error message
             * @example Event not found
             */
            message: string;
            /**
             * @description Optional list of detailed error messages (e.g. validation errors)
             * @default []
             */
            details: string[];
        };
        /** @description Pagination metadata included in list responses. */
        PaginationMeta: {
            /**
             * @description Total number of items matching the query
             * @example 100
             */
            total: number;
            /**
             * @description Current page number (1-based)
             * @example 1
             */
            page: number;
            /**
             * @description Maximum items per page
             * @example 20
             */
            limit: number;
        };
        /** @description Basic user profile returned in auth responses and user listings. */
        UserSummary: {
            /**
             * @description Unique user login identifier
             * @example john_doe
             */
            login: string;
            /**
             * @description User's first name
             * @example John
             */
            firstname: string;
            /**
             * @description User's last name
             * @example Doe
             */
            lastname: string;
            /**
             * Format: email
             * @description User's email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description Whether the user has admin privileges
             * @example false
             */
            is_admin: boolean;
        };
        /** @description Credentials for authentication. */
        AuthLoginRequest: {
            /**
             * @description User login identifier
             * @example john_doe
             */
            username: string;
            /**
             * Format: password
             * @description User password
             * @example secret123
             */
            password: string;
        };
        /** @description Successful authentication response with JWT token and user profile. */
        AuthLoginResponse: {
            /**
             * @description JWT access token (Bearer token for Authorization header)
             * @example eyJhbGciOiJSUzI1NiIs...
             */
            token: string;
            user: components["schemas"]["UserSummary"];
            /**
             * Format: date-time
             * @description Token expiration timestamp (ISO 8601)
             * @example 2026-03-16T12:00:00+00:00
             */
            expires_at: string;
        };
    };
    responses: {
        /** @description Authentication required or token invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "data": null,
                 *       "meta": null,
                 *       "error": {
                 *         "code": 401,
                 *         "message": "Invalid or expired token",
                 *         "details": []
                 *       }
                 *     }
                 */
                "application/json": {
                    data?: null;
                    meta?: null;
                    error?: components["schemas"]["ErrorResponse"];
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "data": null,
                 *       "meta": null,
                 *       "error": {
                 *         "code": 404,
                 *         "message": "Resource not found",
                 *         "details": []
                 *       }
                 *     }
                 */
                "application/json": {
                    data?: null;
                    meta?: null;
                    error?: components["schemas"]["ErrorResponse"];
                };
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "data": null,
                 *       "meta": null,
                 *       "error": {
                 *         "code": 403,
                 *         "message": "Forbidden",
                 *         "details": []
                 *       }
                 *     }
                 */
                "application/json": {
                    data?: null;
                    meta?: null;
                    error?: components["schemas"]["ErrorResponse"];
                };
            };
        };
        /** @description Invalid request parameters or body */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "data": null,
                 *       "meta": null,
                 *       "error": {
                 *         "code": 400,
                 *         "message": "Validation failed",
                 *         "details": [
                 *           "title is required"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": {
                    data?: null;
                    meta?: null;
                    error?: components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["AuthLoginResponse"];
                        meta?: null;
                        error?: null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful (no content) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["AuthLoginResponse"];
                        meta?: null;
                        error?: null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
